"""initial

Revision ID: 2244926e4fd8
Revises: 
Create Date: 2026-07-18 10:32:33.707110+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2244926e4fd8'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Apply the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('name', sa.String(length=255), nullable=False, comment='Human-readable tenant / organization name'),
    sa.Column('slug', sa.String(length=100), nullable=False, comment='URL-safe unique identifier for the tenant'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='Primary contact email for the tenant'),
    sa.Column('github_app_installation_id', sa.String(length=255), nullable=True, comment="GitHub App installation ID for this tenant's org/repos"),
    sa.Column('viasocket_webhook_url', sa.Text(), nullable=True, comment='Tenant-specific viaSocket outbound webhook URL'),
    sa.Column('github_webhook_secret', sa.Text(), nullable=True, comment='Hashed GitHub webhook secret for signature verification'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Whether this tenant is currently active and allowed to use the platform'),
    sa.Column('plan', sa.String(length=50), server_default='free', nullable=False, comment='Subscription plan tier: free | pro | enterprise'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Universally Unique Identifier — primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last-updated timestamp (UTC)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft-delete timestamp (NULL = active record)'),
    sa.PrimaryKeyConstraint('id'),
    comment='Multi-tenant organization registry'
    )
    op.create_index('ix_tenants_created_at', 'tenants', ['created_at'], unique=False)
    op.create_index('ix_tenants_is_active', 'tenants', ['is_active'], unique=False)
    op.create_index(op.f('ix_tenants_slug'), 'tenants', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False, comment='Primary login email'),
    sa.Column('hashed_password', sa.String(length=255), nullable=False, comment='Passlib (bcrypt) hashed password'),
    sa.Column('full_name', sa.String(length=255), nullable=False, comment="User's display name"),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Soft delete / ban flag'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Universally Unique Identifier — primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last-updated timestamp (UTC)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft-delete timestamp (NULL = active record)'),
    sa.PrimaryKeyConstraint('id'),
    comment='Human user identities'
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('api_logs',
    sa.Column('request_id', sa.String(length=100), nullable=False, comment='Unique request ID injected by middleware (also in X-Request-ID response header)'),
    sa.Column('correlation_id', sa.String(length=100), nullable=True, comment='Client-provided correlation ID for distributed tracing'),
    sa.Column('tenant_id', sa.UUID(), nullable=True, comment='Resolved tenant (NULL for unauthenticated requests)'),
    sa.Column('method', sa.String(length=10), nullable=False, comment='HTTP method: GET | POST | PUT | DELETE | PATCH'),
    sa.Column('path', sa.String(length=500), nullable=False, comment='Request path (no query string, no PII)'),
    sa.Column('status_code', sa.Integer(), nullable=False, comment='HTTP response status code'),
    sa.Column('latency_ms', sa.Integer(), nullable=True, comment='Total request processing time in milliseconds'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='Client IP address'),
    sa.Column('user_agent', sa.Text(), nullable=True, comment='HTTP User-Agent'),
    sa.Column('error_detail', sa.Text(), nullable=True, comment='Error summary for non-2xx responses'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Universally Unique Identifier — primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last-updated timestamp (UTC)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft-delete timestamp (NULL = active record)'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id'),
    comment='HTTP API request access log for analytics and debugging'
    )
    op.create_index('ix_api_logs_created_at', 'api_logs', ['created_at'], unique=False)
    op.create_index('ix_api_logs_path', 'api_logs', ['path'], unique=False)
    op.create_index('ix_api_logs_request_id', 'api_logs', ['request_id'], unique=True)
    op.create_index('ix_api_logs_status_code', 'api_logs', ['status_code'], unique=False)
    op.create_index(op.f('ix_api_logs_tenant_id'), 'api_logs', ['tenant_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('tenant_id', sa.UUID(), nullable=True, comment='Tenant context (NULL for pre-auth events like failed key lookups)'),
    sa.Column('actor', sa.String(length=255), nullable=True, comment='Who performed the action (API key prefix, system, webhook source)'),
    sa.Column('actor_type', sa.String(length=50), nullable=False, comment='Actor type: api_key | system | webhook | scheduler'),
    sa.Column('action', sa.String(length=100), nullable=False, comment="Action name (e.g. 'tenant.created', 'job.approved', 'key.revoked')"),
    sa.Column('resource_type', sa.String(length=50), nullable=True, comment='Resource type affected (tenant, job, artifact, api_key)'),
    sa.Column('resource_id', sa.String(length=255), nullable=True, comment='UUID of the affected resource'),
    sa.Column('request_id', sa.String(length=100), nullable=True, comment='Correlation request ID from the HTTP request that triggered this'),
    sa.Column('ip_address', sa.String(length=45), nullable=True, comment='Client IP address (IPv4 or IPv6)'),
    sa.Column('user_agent', sa.Text(), nullable=True, comment='HTTP User-Agent header from the request'),
    sa.Column('old_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='State before the action (for update/delete actions)'),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='State after the action (for create/update actions)'),
    sa.Column('metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional action-specific context'),
    sa.Column('outcome', sa.String(length=20), nullable=False, comment='Result: success | failure | partial'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Universally Unique Identifier — primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last-updated timestamp (UTC)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft-delete timestamp (NULL = active record)'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    comment='Immutable audit trail — never delete these records'
    )
    op.create_index('ix_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_actor', 'audit_logs', ['actor'], unique=False)
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_tenant_id'), 'audit_logs', ['tenant_id'], unique=False)
    op.create_table('jobs',
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='Owning tenant — all access is scoped to this'),
    sa.Column('module', sa.String(length=50), nullable=False, comment='Automation module: scaffolder | test_generator | docs_generator | changelog_generator | notebook_to_blog'),
    sa.Column('trigger', sa.String(length=30), server_default='api', nullable=False, comment='What initiated this job: api | webhook_github | webhook_ci | mcp | cli | scheduled'),
    sa.Column('status', sa.String(length=30), server_default='queued', nullable=False, comment='Current job status'),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Module-specific input payload (validated per module)'),
    sa.Column('result', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment="Module output — ModuleResult.output from Dev 1's handler"),
    sa.Column('error', sa.Text(), nullable=True, comment='Error message if job failed — never expose raw tracebacks in API responses'),
    sa.Column('celery_task_id', sa.String(length=255), nullable=True, comment='Celery task UUID — used for status tracking and idempotency'),
    sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False, comment='Number of Celery retries attempted'),
    sa.Column('priority', sa.Integer(), server_default='5', nullable=False, comment='Queue priority (1=highest, 10=lowest)'),
    sa.Column('started_at', sa.DateTime(), nullable=True, comment='Timestamp when worker picked up and started executing the job'),
    sa.Column('completed_at', sa.DateTime(), nullable=True, comment='Timestamp when job reached terminal state (success/failed/cancelled)'),
    sa.Column('requires_approval', sa.Boolean(), server_default='false', nullable=False, comment='True for notebook_to_blog jobs — must be approved before viaSocket dispatch'),
    sa.Column('approved_by', sa.String(length=255), nullable=True, comment='Identifier of who approved/rejected (email or user ID from Dev 2)'),
    sa.Column('approval_note', sa.Text(), nullable=True, comment='Optional note from the approver/rejecter'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Universally Unique Identifier — primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last-updated timestamp (UTC)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft-delete timestamp (NULL = active record)'),
    sa.CheckConstraint("module IN ('scaffolder', 'test_generator', 'docs_generator', 'changelog_generator', 'notebook_to_blog')", name='ck_jobs_module'),
    sa.CheckConstraint("status IN ('queued', 'running', 'success', 'failed', 'partial', 'cancelled', 'approval_pending', 'approved', 'rejected')", name='ck_jobs_status'),
    sa.CheckConstraint("trigger IN ('api', 'webhook_github', 'webhook_ci', 'mcp', 'cli', 'scheduled')", name='ck_jobs_trigger'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='Central job registry — every automation request is a job'
    )
    op.create_index('ix_jobs_celery_task_id', 'jobs', ['celery_task_id'], unique=False)
    op.create_index('ix_jobs_created_at', 'jobs', ['created_at'], unique=False)
    op.create_index('ix_jobs_status', 'jobs', ['status'], unique=False)
    op.create_index(op.f('ix_jobs_tenant_id'), 'jobs', ['tenant_id'], unique=False)
    op.create_index('ix_jobs_tenant_module', 'jobs', ['tenant_id', 'module'], unique=False)
    op.create_index('ix_jobs_tenant_status', 'jobs', ['tenant_id', 'status'], unique=False)
    op.create_table('retry_queue',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('operation_type', sa.String(length=50), nullable=False, comment='Type: job_execution | viasocket_dispatch | webhook_processing'),
    sa.Column('reference_id', sa.String(length=255), nullable=False, comment='UUID of the failed resource (job_id, dispatch_id, webhook_event_id)'),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Full payload needed to replay this operation'),
    sa.Column('failure_reason', sa.Text(), nullable=False, comment='Last failure error message'),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False, comment='Status: pending | replayed | resolved | discarded'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Universally Unique Identifier — primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last-updated timestamp (UTC)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft-delete timestamp (NULL = active record)'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='Dead-letter queue for failed async operations requiring manual retry'
    )
    op.create_index('ix_retry_queue_operation_type', 'retry_queue', ['operation_type'], unique=False)
    op.create_index('ix_retry_queue_status', 'retry_queue', ['status'], unique=False)
    op.create_index('ix_retry_queue_tenant_id', 'retry_queue', ['tenant_id'], unique=False)
    op.create_table('tenant_members',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=50), server_default='developer', nullable=False, comment='RBAC role: owner | admin | developer | viewer'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Universally Unique Identifier — primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last-updated timestamp (UTC)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft-delete timestamp (NULL = active record)'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'tenant_id', name='uq_tenant_member_user_tenant'),
    comment='User roles within a specific tenant'
    )
    op.create_index(op.f('ix_tenant_members_tenant_id'), 'tenant_members', ['tenant_id'], unique=False)
    op.create_index(op.f('ix_tenant_members_user_id'), 'tenant_members', ['user_id'], unique=False)
    op.create_table('tenant_secrets',
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='Owner tenant'),
    sa.Column('key_hash', sa.String(length=128), nullable=False, comment='SHA-256 hex digest of the raw API key — never store plaintext'),
    sa.Column('key_prefix', sa.String(length=16), nullable=False, comment='First 8 chars of the raw key for display identification (sf_xxxxxxxx...)'),
    sa.Column('name', sa.String(length=100), nullable=True, comment="User-assigned label for this key (e.g. 'CI Key', 'Dev Key')"),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False, comment='Whether this specific key is currently valid'),
    sa.Column('last_used_at', sa.DateTime(), nullable=True, comment='Timestamp of last successful authentication with this key'),
    sa.Column('expires_at', sa.DateTime(), nullable=True, comment='Optional expiry timestamp — NULL means never expires'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Universally Unique Identifier — primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last-updated timestamp (UTC)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft-delete timestamp (NULL = active record)'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash'),
    comment='Hashed API keys for tenant authentication'
    )
    op.create_index('ix_tenant_secrets_key_hash', 'tenant_secrets', ['key_hash'], unique=True)
    op.create_index(op.f('ix_tenant_secrets_tenant_id'), 'tenant_secrets', ['tenant_id'], unique=False)
    op.create_table('artifacts',
    sa.Column('job_id', sa.UUID(), nullable=False, comment='Job that produced this artifact'),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='Owning tenant — for direct filtering without JOIN'),
    sa.Column('file_name', sa.String(length=500), nullable=False, comment="Original file name (e.g. 'test_auth.py', 'CHANGELOG.md')"),
    sa.Column('s3_key', sa.String(length=1000), nullable=False, comment='MinIO object key path: {tenant_id}/{job_id}/{filename}'),
    sa.Column('content_type', sa.String(length=100), nullable=False, comment='MIME type (text/markdown, text/x-python, application/zip, etc.)'),
    sa.Column('size_bytes', sa.BigInteger(), nullable=True, comment='File size in bytes'),
    sa.Column('version', sa.Integer(), server_default='1', nullable=False, comment='Version number — allows re-generation without losing history'),
    sa.Column('checksum', sa.String(length=128), nullable=True, comment='SHA-256 hex checksum of file contents for integrity verification'),
    sa.Column('artifact_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Module-specific metadata (e.g. test coverage %, doc sections generated)'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Universally Unique Identifier — primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last-updated timestamp (UTC)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft-delete timestamp (NULL = active record)'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('s3_key'),
    comment='Generated artifact metadata — files stored in MinIO'
    )
    op.create_index('ix_artifacts_content_type', 'artifacts', ['content_type'], unique=False)
    op.create_index(op.f('ix_artifacts_job_id'), 'artifacts', ['job_id'], unique=False)
    op.create_index('ix_artifacts_tenant_id', 'artifacts', ['tenant_id'], unique=False)
    op.create_table('job_logs',
    sa.Column('job_id', sa.UUID(), nullable=False),
    sa.Column('level', sa.String(length=10), nullable=False, comment='Log level: DEBUG | INFO | WARNING | ERROR | CRITICAL'),
    sa.Column('event', sa.String(length=100), nullable=False, comment="Machine-readable event name (e.g. 'job.started', 'llm.called')"),
    sa.Column('message', sa.Text(), nullable=False, comment='Human-readable log message'),
    sa.Column('context', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Structured key-value context for this log event'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Universally Unique Identifier — primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last-updated timestamp (UTC)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft-delete timestamp (NULL = active record)'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='Granular execution timeline for each job'
    )
    op.create_index('ix_job_logs_job_id', 'job_logs', ['job_id'], unique=False)
    op.create_index('ix_job_logs_level', 'job_logs', ['level'], unique=False)
    op.create_table('llm_usage',
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='Tenant charged for this LLM call'),
    sa.Column('job_id', sa.UUID(), nullable=True, comment='Job that triggered this LLM call (NULL for system calls)'),
    sa.Column('provider', sa.String(length=50), nullable=False, comment='LLM provider: google | anthropic'),
    sa.Column('model', sa.String(length=100), nullable=False, comment="Model identifier (e.g. 'gemini-1.5-pro', 'claude-sonnet-4-6')"),
    sa.Column('input_tokens', sa.Integer(), nullable=False, comment='Number of input/prompt tokens consumed'),
    sa.Column('output_tokens', sa.Integer(), nullable=False, comment='Number of output/completion tokens generated'),
    sa.Column('total_tokens', sa.Integer(), nullable=False, comment='Total tokens (input + output) for simplified queries'),
    sa.Column('estimated_cost_usd', sa.Numeric(precision=10, scale=8), nullable=True, comment='Estimated cost in USD based on model pricing at time of call'),
    sa.Column('latency_ms', sa.Integer(), nullable=True, comment='End-to-end latency in milliseconds for this LLM call'),
    sa.Column('retry_count', sa.Integer(), server_default='0', nullable=False, comment='Number of retries before this call succeeded'),
    sa.Column('success', sa.Boolean(), server_default='true', nullable=False, comment='Whether this LLM call completed successfully'),
    sa.Column('operation', sa.String(length=100), nullable=True, comment="High-level operation label (e.g. 'scaffold.generate', 'docs.summarize')"),
    sa.Column('request_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional request context (system prompt hash, message count, etc.)'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Universally Unique Identifier — primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last-updated timestamp (UTC)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft-delete timestamp (NULL = active record)'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='Per-call LLM token and cost tracking for billing and observability'
    )
    op.create_index('ix_llm_usage_created_at', 'llm_usage', ['created_at'], unique=False)
    op.create_index('ix_llm_usage_job_id', 'llm_usage', ['job_id'], unique=False)
    op.create_index('ix_llm_usage_model', 'llm_usage', ['model'], unique=False)
    op.create_index('ix_llm_usage_tenant_id', 'llm_usage', ['tenant_id'], unique=False)
    op.create_table('notifications',
    sa.Column('tenant_id', sa.UUID(), nullable=False),
    sa.Column('job_id', sa.UUID(), nullable=True),
    sa.Column('notification_type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('is_read', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('notification_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Additional structured data for the notification'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Universally Unique Identifier — primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last-updated timestamp (UTC)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft-delete timestamp (NULL = active record)'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    comment='System notifications for tenant dashboard consumption'
    )
    op.create_index('ix_notifications_is_read', 'notifications', ['is_read'], unique=False)
    op.create_index(op.f('ix_notifications_tenant_id'), 'notifications', ['tenant_id'], unique=False)
    op.create_index('ix_notifications_type', 'notifications', ['notification_type'], unique=False)
    op.create_table('viasocket_dispatches',
    sa.Column('job_id', sa.UUID(), nullable=False, comment='Job whose completion triggered this dispatch'),
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='Tenant for direct filtering'),
    sa.Column('event_name', sa.String(length=100), nullable=False, comment='viaSocket event name (from events.py enum)'),
    sa.Column('payload_sent', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Full JSON payload sent to viaSocket endpoint'),
    sa.Column('target_url', sa.Text(), nullable=False, comment='viaSocket webhook URL the payload was POSTed to'),
    sa.Column('status_code', sa.Integer(), nullable=True, comment='HTTP status code from viaSocket (None if request never completed)'),
    sa.Column('response_body', sa.Text(), nullable=True, comment='Response body from viaSocket (truncated to 2000 chars)'),
    sa.Column('error_message', sa.Text(), nullable=True, comment='Error message if dispatch failed at network/transport level'),
    sa.Column('attempt_count', sa.Integer(), server_default='1', nullable=False, comment='Which attempt this is (1 = first try, 2 = first retry, etc.)'),
    sa.Column('status', sa.String(length=20), server_default='pending', nullable=False, comment='Dispatch status: pending | success | failed | retrying | dead_lettered'),
    sa.Column('next_retry_at', sa.DateTime(), nullable=True, comment='When to attempt the next retry (NULL if no retry scheduled)'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Universally Unique Identifier — primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last-updated timestamp (UTC)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft-delete timestamp (NULL = active record)'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='Outbound viaSocket dispatch audit log with retry history'
    )
    op.create_index(op.f('ix_viasocket_dispatches_job_id'), 'viasocket_dispatches', ['job_id'], unique=False)
    op.create_index('ix_viasocket_dispatches_status', 'viasocket_dispatches', ['status'], unique=False)
    op.create_index('ix_viasocket_dispatches_tenant_id', 'viasocket_dispatches', ['tenant_id'], unique=False)
    op.create_table('webhook_events',
    sa.Column('tenant_id', sa.UUID(), nullable=False, comment='Tenant this webhook belongs to'),
    sa.Column('source', sa.String(length=30), nullable=False, comment='Webhook origin: github | ci | other'),
    sa.Column('event_type', sa.String(length=100), nullable=False, comment="Specific event type from source (e.g. 'push', 'release', 'workflow_run')"),
    sa.Column('delivery_id', sa.String(length=255), nullable=True, comment='GitHub X-GitHub-Delivery header — used for deduplication'),
    sa.Column('raw_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='Complete raw webhook payload — never modified after insert'),
    sa.Column('headers', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Sanitized inbound HTTP headers (signature header excluded for security)'),
    sa.Column('processed', sa.Boolean(), server_default='false', nullable=False, comment='Whether this event has been successfully processed'),
    sa.Column('processing_error', sa.Text(), nullable=True, comment='Error message if processing failed'),
    sa.Column('job_id', sa.UUID(), nullable=True, comment='Job created in response to this webhook (NULL if not yet processed)'),
    sa.Column('received_at', sa.DateTime(), nullable=False, comment='Timestamp when the webhook request arrived'),
    sa.Column('id', sa.UUID(), nullable=False, comment='Universally Unique Identifier — primary key'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record creation timestamp (UTC)'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Record last-updated timestamp (UTC)'),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True, comment='Soft-delete timestamp (NULL = active record)'),
    sa.ForeignKeyConstraint(['job_id'], ['jobs.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    comment='Inbound webhook events — stored before processing (store-first pattern)'
    )
    op.create_index(op.f('ix_webhook_events_processed'), 'webhook_events', ['processed'], unique=False)
    op.create_index('ix_webhook_events_received_at', 'webhook_events', ['received_at'], unique=False)
    op.create_index('ix_webhook_events_source_type', 'webhook_events', ['source', 'event_type'], unique=False)
    op.create_index('ix_webhook_events_tenant_id', 'webhook_events', ['tenant_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert the migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_webhook_events_tenant_id', table_name='webhook_events')
    op.drop_index('ix_webhook_events_source_type', table_name='webhook_events')
    op.drop_index('ix_webhook_events_received_at', table_name='webhook_events')
    op.drop_index(op.f('ix_webhook_events_processed'), table_name='webhook_events')
    op.drop_table('webhook_events')
    op.drop_index('ix_viasocket_dispatches_tenant_id', table_name='viasocket_dispatches')
    op.drop_index('ix_viasocket_dispatches_status', table_name='viasocket_dispatches')
    op.drop_index(op.f('ix_viasocket_dispatches_job_id'), table_name='viasocket_dispatches')
    op.drop_table('viasocket_dispatches')
    op.drop_index('ix_notifications_type', table_name='notifications')
    op.drop_index(op.f('ix_notifications_tenant_id'), table_name='notifications')
    op.drop_index('ix_notifications_is_read', table_name='notifications')
    op.drop_table('notifications')
    op.drop_index('ix_llm_usage_tenant_id', table_name='llm_usage')
    op.drop_index('ix_llm_usage_model', table_name='llm_usage')
    op.drop_index('ix_llm_usage_job_id', table_name='llm_usage')
    op.drop_index('ix_llm_usage_created_at', table_name='llm_usage')
    op.drop_table('llm_usage')
    op.drop_index('ix_job_logs_level', table_name='job_logs')
    op.drop_index('ix_job_logs_job_id', table_name='job_logs')
    op.drop_table('job_logs')
    op.drop_index('ix_artifacts_tenant_id', table_name='artifacts')
    op.drop_index(op.f('ix_artifacts_job_id'), table_name='artifacts')
    op.drop_index('ix_artifacts_content_type', table_name='artifacts')
    op.drop_table('artifacts')
    op.drop_index(op.f('ix_tenant_secrets_tenant_id'), table_name='tenant_secrets')
    op.drop_index('ix_tenant_secrets_key_hash', table_name='tenant_secrets')
    op.drop_table('tenant_secrets')
    op.drop_index(op.f('ix_tenant_members_user_id'), table_name='tenant_members')
    op.drop_index(op.f('ix_tenant_members_tenant_id'), table_name='tenant_members')
    op.drop_table('tenant_members')
    op.drop_index('ix_retry_queue_tenant_id', table_name='retry_queue')
    op.drop_index('ix_retry_queue_status', table_name='retry_queue')
    op.drop_index('ix_retry_queue_operation_type', table_name='retry_queue')
    op.drop_table('retry_queue')
    op.drop_index('ix_jobs_tenant_status', table_name='jobs')
    op.drop_index('ix_jobs_tenant_module', table_name='jobs')
    op.drop_index(op.f('ix_jobs_tenant_id'), table_name='jobs')
    op.drop_index('ix_jobs_status', table_name='jobs')
    op.drop_index('ix_jobs_created_at', table_name='jobs')
    op.drop_index('ix_jobs_celery_task_id', table_name='jobs')
    op.drop_table('jobs')
    op.drop_index(op.f('ix_audit_logs_tenant_id'), table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_api_logs_tenant_id'), table_name='api_logs')
    op.drop_index('ix_api_logs_status_code', table_name='api_logs')
    op.drop_index('ix_api_logs_request_id', table_name='api_logs')
    op.drop_index('ix_api_logs_path', table_name='api_logs')
    op.drop_index('ix_api_logs_created_at', table_name='api_logs')
    op.drop_table('api_logs')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_tenants_slug'), table_name='tenants')
    op.drop_index('ix_tenants_is_active', table_name='tenants')
    op.drop_index('ix_tenants_created_at', table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
