import io
import zipfile
import logging
from typing import Dict, Any
from engine.core.models import ModuleResult
from engine.core import storage
from engine.core import llm_client
from engine.prompts.scaffolder import README_CUSTOMIZATION_PROMPT

logger = logging.getLogger("engine.modules.scaffolder")

# Simple templates embedded in the code for robustness
FASTAPI_TEMPLATES = {
    "main.py": """from fastapi import FastAPI

app = FastAPI(title="{project_name}")

@app.get("/")
def read_root():
    return {{"message": "Welcome to {project_name}! Generated by ShipFaster."}}

@app.get("/health")
def health_check():
    return {{"status": "healthy"}}
""",
    "requirements.txt": """fastapi>=0.100.0
uvicorn>=0.22.0
pytest>=7.0.0
""",
    "tests/test_main.py": """from fastapi.testclient import TestClient
from main import app

client = TestClient(app)

def test_read_root():
    response = client.get("/")
    assert response.status_code == 200
    assert "Welcome" in response.json()["message"]

def test_health():
    response = client.get("/health")
    assert response.status_code == 200
    assert response.json() == {{"status": "healthy"}}
"""
}

async def run(job_id: str, tenant_id: str, payload: dict) -> ModuleResult:
    """
    Scaffolder module handler.
    Generates a project skeleton for the specified stack, packages it as a zip file,
    and saves it to storage.
    
    Payload shape:
    {
        "stack": str,         # e.g., "fastapi"
        "project_name": str,  # e.g., "my_api_project"
        "description": str    # optional description for README customization
    }
    """
    stack = payload.get("stack", "fastapi").lower()
    project_name = payload.get("project_name", "shipfaster_project")
    description = payload.get("description", "A fast API project generated by ShipFaster.")
    
    if stack != "fastapi":
        return ModuleResult(
            status="failed",
            output={},
            artifacts=[],
            error=f"Unsupported stack: '{stack}'. Only 'fastapi' is currently supported."
        )
        
    try:
        # 1. Custom README generation via LLM if a description is provided
        logger.info(f"Customizing README for project: {project_name}")
        system_instruction = README_CUSTOMIZATION_PROMPT.format(
            project_name=project_name,
            stack=stack,
            description=description
        )
        
        # We do a quick LLM call to get the customized README
        readme_content = await llm_client.complete(
            tenant_id=tenant_id,
            job_id=job_id,
            system=system_instruction,
            messages=[{"role": "user", "content": "Please generate the README.md"}]
        )
        
        # 2. Package files into a zip file in memory
        zip_buffer = io.BytesIO()
        with zipfile.ZipFile(zip_buffer, "w", zipfile.ZIP_DEFLATED) as zip_file:
            # Write project template files
            for file_path, template_str in FASTAPI_TEMPLATES.items():
                content = template_str.format(project_name=project_name)
                zip_file.writestr(file_path, content)
                
            # Write custom README
            zip_file.writestr("README.md", readme_content)
            
        zip_bytes = zip_buffer.getvalue()
        
        # 3. Save zip archive to storage
        artifact_name = f"{project_name}.zip"
        s3_key = storage.save_artifact(
            job_id=job_id,
            tenant_id=tenant_id,
            file_name=artifact_name,
            file_content=zip_bytes,
            content_type="application/zip"
        )
        
        return ModuleResult(
            status="success",
            output={
                "artifact_key": s3_key,
                "project_name": project_name,
                "stack": stack,
                "readme_summary": readme_content[:200] + "..."
            },
            artifacts=[s3_key],
            error=None
        )
        
    except Exception as e:
        logger.error(f"Error in scaffolder module execution: {str(e)}")
        return ModuleResult(
            status="failed",
            output={},
            artifacts=[],
            error=str(e)
        )
