"""
Artifact Model.

Artifacts are the output files generated by ShipFaster modules:
- Scaffolded project files
- Generated test files
- Documentation (Markdown/HTML)
- Changelogs
- Blog posts from notebooks

Files are stored in MinIO. This table stores metadata only.
"""

import uuid
from typing import Any

from sqlalchemy import BigInteger, ForeignKey, Index, Integer, String, Text
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from engine.core.models.base import TimestampedModel


class Artifact(TimestampedModel):
    """
    Metadata for a generated artifact stored in MinIO/S3.

    The actual file bytes live in MinIO. This table records
    where to find them, what they are, and their association
    to a job and tenant.
    """

    __tablename__ = "artifacts"
    __table_args__ = (
        Index("ix_artifacts_job_id", "job_id"),
        Index("ix_artifacts_tenant_id", "tenant_id"),
        Index("ix_artifacts_content_type", "content_type"),
        {"comment": "Generated artifact metadata — files stored in MinIO"},
    )

    # --- Foreign Keys ---
    job_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("jobs.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
        comment="Job that produced this artifact",
    )
    tenant_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("tenants.id", ondelete="RESTRICT"),
        nullable=False,
        index=True,
        comment="Owning tenant — for direct filtering without JOIN",
    )

    # --- File Metadata ---
    file_name: Mapped[str] = mapped_column(
        String(500),
        nullable=False,
        comment="Original file name (e.g. 'test_auth.py', 'CHANGELOG.md')",
    )
    s3_key: Mapped[str] = mapped_column(
        String(1000),
        nullable=False,
        unique=True,
        comment="MinIO object key path: {tenant_id}/{job_id}/{filename}",
    )
    content_type: Mapped[str] = mapped_column(
        String(100),
        nullable=False,
        default="application/octet-stream",
        comment="MIME type (text/markdown, text/x-python, application/zip, etc.)",
    )
    size_bytes: Mapped[int | None] = mapped_column(
        BigInteger,
        nullable=True,
        comment="File size in bytes",
    )

    # --- Versioning ---
    version: Mapped[int] = mapped_column(
        Integer,
        nullable=False,
        default=1,
        server_default="1",
        comment="Version number — allows re-generation without losing history",
    )
    checksum: Mapped[str | None] = mapped_column(
        String(128),
        nullable=True,
        comment="SHA-256 hex checksum of file contents for integrity verification",
    )

    # --- Extra Metadata ---
    artifact_metadata: Mapped[dict[str, Any] | None] = mapped_column(
        JSONB,
        nullable=True,
        comment="Module-specific metadata (e.g. test coverage %, doc sections generated)",
    )

    # --- Relationships ---
    job: Mapped["Job"] = relationship(  # type: ignore[name-defined]
        "Job",
        back_populates="artifacts",
        lazy="select",
    )

    def __repr__(self) -> str:
        return f"<Artifact id={self.id} file={self.file_name!r} job={self.job_id}>"
