"""
Notification Model.

System-generated notifications to tenants triggered by job events:
- Job completion/failure
- Approval requests
- viaSocket dispatch failures
- System alerts

Can be consumed by Dev 2's frontend via polling or WebSocket.
"""

import uuid
from typing import Any

from sqlalchemy import Boolean, ForeignKey, Index, String, Text
from sqlalchemy.dialects.postgresql import JSONB, UUID
from sqlalchemy.orm import Mapped, mapped_column

from engine.core.models.base import TimestampedModel


NOTIFICATION_TYPES = (
    "job_completed",
    "job_failed",
    "approval_required",
    "artifact_ready",
    "dispatch_failed",
    "system_alert",
)


class Notification(TimestampedModel):
    """
    Tenant-scoped notification record.

    Generated by the system when notable events occur.
    Dev 2 polls GET /api/v1/notifications to display these in the dashboard.
    """

    __tablename__ = "notifications"
    __table_args__ = (
        Index("ix_notifications_tenant_id", "tenant_id"),
        Index("ix_notifications_is_read", "is_read"),
        Index("ix_notifications_type", "notification_type"),
        {"comment": "System notifications for tenant dashboard consumption"},
    )

    tenant_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("tenants.id", ondelete="CASCADE"),
        nullable=False,
        index=True,
    )
    job_id: Mapped[uuid.UUID | None] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("jobs.id", ondelete="SET NULL"),
        nullable=True,
    )
    notification_type: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
    )
    title: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
    )
    body: Mapped[str | None] = mapped_column(
        Text,
        nullable=True,
    )
    is_read: Mapped[bool] = mapped_column(
        Boolean,
        nullable=False,
        default=False,
        server_default="false",
        index=True,
    )
    notification_data: Mapped[dict[str, Any] | None] = mapped_column(
        JSONB,
        nullable=True,
        comment="Additional structured data for the notification",
    )

    def __repr__(self) -> str:
        return f"<Notification type={self.notification_type!r} read={self.is_read}>"


class RetryQueue(TimestampedModel):
    """
    Dead-letter and retry queue for failed async operations.

    When Celery retries are exhausted or a viaSocket dispatch permanently fails,
    a RetryQueue entry is created for manual inspection and potential replay.
    """

    __tablename__ = "retry_queue"
    __table_args__ = (
        Index("ix_retry_queue_status", "status"),
        Index("ix_retry_queue_operation_type", "operation_type"),
        Index("ix_retry_queue_tenant_id", "tenant_id"),
        {"comment": "Dead-letter queue for failed async operations requiring manual retry"},
    )

    tenant_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True),
        ForeignKey("tenants.id", ondelete="RESTRICT"),
        nullable=False,
    )
    operation_type: Mapped[str] = mapped_column(
        String(50),
        nullable=False,
        comment="Type: job_execution | viasocket_dispatch | webhook_processing",
    )
    reference_id: Mapped[str] = mapped_column(
        String(255),
        nullable=False,
        comment="UUID of the failed resource (job_id, dispatch_id, webhook_event_id)",
    )
    payload: Mapped[dict[str, Any]] = mapped_column(
        JSONB,
        nullable=False,
        comment="Full payload needed to replay this operation",
    )
    failure_reason: Mapped[str] = mapped_column(
        Text,
        nullable=False,
        comment="Last failure error message",
    )
    attempt_count: Mapped[int] = mapped_column(
        nullable=False,
        default=1,
    )
    status: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        default="pending",
        comment="Status: pending | replayed | resolved | discarded",
    )

    def __repr__(self) -> str:
        return f"<RetryQueue op={self.operation_type!r} ref={self.reference_id!r} status={self.status!r}>"
